window.WashModules = window.WashModules || {};
window.WashModules.reuniones = window.WashModules.reuniones || {};

(function(){
  const state = { ctx:null, lastResult:null, file:null };
  const PROMPT_FALLBACK = {
    system:'Eres WASH-OS, asistente institucional UNICEF/WASH para reuniones técnicas y seguimiento operativo.',
    summary:'Genera un resumen ejecutivo corto y claro.',
    agreements:'Identifica acuerdos y decisiones.',
    tasks:'Convierte la reunión en tareas accionables con responsable, fecha, prioridad y acción concreta.',
    risks:'Detecta riesgos, bloqueos, retrasos y brechas de información.',
    next_steps:'Genera próximos pasos operativos inmediatos.',
    executive_minutes:'Prepara una minuta ejecutiva breve con enfoque WASH/UNICEF.'
  };

  function esc(value){return String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function get(id){return document.getElementById(id);}
  function setStatus(text){const el=get('meet-ai-status');if(el)el.textContent=text;}
  function getRoute(){return window.WashAI&&typeof window.WashAI.routeAI==='function'?window.WashAI.routeAI('meeting'):{provider:'openai',model:'meeting-fallback'};}
  function getPromptUrl(){return state.ctx&&state.ctx.resolveAppPath?state.ctx.resolveAppPath('/config/prompts/reuniones.json'):'/config/prompts/reuniones.json';}
  async function loadMeetingPrompts(){try{const res=await fetch(getPromptUrl(),{cache:'no-cache'});if(!res.ok)throw new Error(res.status);return {...PROMPT_FALLBACK,...await res.json()};}catch(e){console.warn('No se pudo cargar prompts de reuniones, usando fallback.',e);return PROMPT_FALLBACK;}}
  function list(items, empty){return (items&&items.length)?items.map(i=>`<li>${esc(typeof i==='string'?i:(i.action||i.text||i.descripcion||JSON.stringify(i)))}</li>`).join(''):`<li style="color:#94a3b8">${empty}</li>`;}
  function taskList(tasks){return (tasks&&tasks.length)?tasks.map(t=>`<div class="meet-task"><div><strong>${esc(t.action||t.tarea||t.text||'Tarea')}</strong></div><div class="meet-meta">👤 ${esc(t.responsible||t.responsable||'No especificado')} · 📅 ${esc(t.date||t.fecha||'No especificado')} · ⚑ ${esc(t.priority||t.prioridad||'Media')}</div></div>`).join(''):'<div class="meet-empty">No se identificaron tareas.</div>';}
  function meetingInput(){return {title:get('meet-title')?.value.trim()||'Reunión sin título',date:get('meet-date')?.value||'',type:get('meet-type')?.value||'Reunión técnica',content:get('meet-notes')?.value.trim()||'',fileName:state.file?.name||'',fileType:state.file?.type||''};}
  function buildPrompt(input,prompts,route){return `${prompts.system}\n\nTIPO DE REUNIÓN: ${input.type}\nTÍTULO: ${input.title}\nFECHA: ${input.date||'No especificada'}\nARCHIVO: ${input.fileName||'Sin archivo'} (${input.fileType||'notas rápidas'})\nMODELO SUGERIDO: ${route.provider}/${route.model}\n\nPIPELINE MULTIMODAL:\n- audio → transcripción futura\n- PDF → extracción de texto / OCR preparado\n- DOCX → lectura estructurada\n- imagen → OCR preparado\n- TXT/notas → análisis directo\n\nINSTRUCCIONES:\n1. ${prompts.summary}\n2. ${prompts.agreements}\n3. ${prompts.tasks}\n4. ${prompts.risks}\n5. ${prompts.next_steps}\n6. ${prompts.executive_minutes||'Genera una minuta ejecutiva breve.'}\n\nResponde únicamente en JSON válido con esta estructura:\n{\n  "summary":"",\n  "agreements":[""],\n  "tasks":[{"action":"","responsible":"No especificado","date":"No especificado","priority":"Media"}],\n  "risks":[""],\n  "next_steps":[""]\n}\n\nCONTENIDO MULTIMODAL NORMALIZADO:\n${input.content}`;}
  function parseLines(text,label){const re=new RegExp(`${label}[:\\n]+([\\s\\S]*?)(\\n[A-ZÁÉÍÓÚ_ ]{4,}:|$)`,'i');const m=text.match(re);return m?m[1].split(/\n|;/).map(x=>x.replace(/^[-*\d.\s]+/,'').trim()).filter(Boolean):[];}
  function parseResult(text){try{const parsed=JSON.parse(text);return {summary:parsed.summary||parsed.resumen||'',agreements:parsed.agreements||parsed.acuerdos||[],tasks:parsed.tasks||parsed.tareas||[],risks:parsed.risks||parsed.riesgos||[],next_steps:parsed.next_steps||parsed.proximos_pasos||parsed.nextSteps||[]};}catch(e){}
    return {summary:text.split('\n').slice(0,4).join('\n').trim(),agreements:parseLines(text,'ACUERDOS|AGREEMENTS'),tasks:parseLines(text,'TAREAS|TASKS').map(action=>({action,responsible:'No especificado',date:'No especificado',priority:'Media'})),risks:parseLines(text,'RIESGOS|RISKS'),next_steps:parseLines(text,'PRÓXIMOS PASOS|NEXT STEPS')};}
  function renderResults(result){const box=get('meet-results');if(!box)return;box.style.display='grid';box.innerHTML=`<div class="meet-result-card"><h3>Resumen</h3><p>${esc(result.summary||'Sin resumen.')}</p></div><div class="meet-result-card"><h3>Acuerdos</h3><ul>${list(result.agreements,'No se identificaron acuerdos.')}</ul></div><div class="meet-result-card"><h3>Tareas</h3>${taskList(result.tasks)}</div><div class="meet-result-card"><h3>Riesgos</h3><ul>${list(result.risks,'No se identificaron riesgos.')}</ul></div><div class="meet-result-card"><h3>Próximos pasos</h3><ul>${list(result.next_steps,'No se identificaron próximos pasos.')}</ul></div><div class="meet-result-card"><h3>Exportación</h3><button onclick="WashMeetings.exportHTML()">Exportar HTML / PDF</button></div>`;}
  async function saveResult(input,result){if(!state.ctx||!state.ctx.historialReuniones)return;const contenido=[result.summary,(result.agreements||[]).join('\n'),(result.next_steps||[]).join('\n')].filter(Boolean).join('\n\n');state.ctx.historialReuniones.unshift({titulo:input.title,fecha:input.date,tipo:input.type,lugar:'',contenido,resumen:result.summary,archivoNombre:input.fileName,archivoTipo:input.fileType,resultado:result,tareas:result.tasks||[],ts:Date.now()});if(state.ctx.saveHist)await state.ctx.saveHist('hist-reuniones',state.ctx.historialReuniones);}

  window.WashMeetings = {
    async process(){const input=meetingInput();if(!input.content){alert('Agrega notas, transcripción o un archivo multimodal.');return;}const route=getRoute();const prompts=await loadMeetingPrompts();const prompt=buildPrompt(input,prompts,route);setStatus(`AI Router: ${route.provider} · ${route.model}`);const paste=get('meet-ai-paste');if(paste)paste.style.display='block';try{if(typeof sendPrompt==='function'){sendPrompt(prompt);setStatus(`Enviado a ${route.provider}. Pega el JSON de respuesta abajo.`);}else throw new Error('sendPrompt unavailable');}catch(e){navigator.clipboard.writeText(prompt).then(()=>setStatus(`Prompt copiado para ${route.provider}. Pega el JSON de respuesta abajo.`)).catch(()=>setStatus('No se pudo enviar/copiar. Copia manualmente las notas.'));}},
    async loadResult(){const raw=get('meet-ai-output')?.value.trim();if(!raw){alert('Pega el JSON o resultado primero.');return;}const input=meetingInput();const result=parseResult(raw);state.lastResult={input,result};renderResults(result);await saveResult(input,result);setStatus('Resultado guardado en historial de reuniones.');},
    async handleFile(file){if(!file)return;const preview={name:file.name,type:'detectando',label:'Detectando',icon:'📎',status:'procesando',note:'Procesando archivo...'};window.WashMeetingsUI.setFilePreview(preview);try{const fileInfo=await window.WashMeetingProcessors.processFile(file);state.file=fileInfo;window.WashMeetingsUI.setFilePreview(fileInfo);const notes=get('meet-notes');if(notes)notes.value=fileInfo.text;setStatus(`${fileInfo.label} listo · ${fileInfo.note}`);}catch(e){console.warn('No se pudo procesar el archivo de reunión.',e);window.WashMeetingsUI.setFilePreview({name:file.name,label:'Error',icon:'⚠️',status:'pendiente',note:'No se pudo procesar. Pega el contenido manualmente.'});setStatus('No se pudo procesar el archivo.');}},
    exportHTML(){if(!state.lastResult){alert('Procesa y carga un resultado primero.');return;}const {input,result}=state.lastResult;const html=`<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>${esc(input.title)}</title><style>body{font-family:Arial,sans-serif;padding:32px;line-height:1.6;color:#1e293b}h1{color:#0f766e}.card{border:1px solid #e2e8f0;border-radius:10px;padding:14px;margin:12px 0}li{margin:4px 0}@media print{button{display:none}}</style></head><body><h1>${esc(input.title)}</h1><p>${esc(input.type)} · ${esc(input.date||'Sin fecha')} · ${esc(input.fileName||'Sin archivo')}</p><div class="card"><h2>Resumen</h2><p>${esc(result.summary)}</p></div><div class="card"><h2>Acuerdos</h2><ul>${list(result.agreements,'Sin acuerdos')}</ul></div><div class="card"><h2>Tareas</h2>${taskList(result.tasks)}</div><div class="card"><h2>Riesgos</h2><ul>${list(result.risks,'Sin riesgos')}</ul></div><div class="card"><h2>Próximos pasos</h2><ul>${list(result.next_steps,'Sin próximos pasos')}</ul></div></body></html>`;if(state.ctx&&state.ctx.dlBlob)state.ctx.dlBlob(html,`reunion_${Date.now()}.html`);else{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'text/html'}));a.download=`reunion_${Date.now()}.html`;a.click();URL.revokeObjectURL(a.href);}}
  };

  window.WashModules.reuniones.render = function(ctx){state.ctx=ctx;return window.WashMeetingsUI.render(ctx,getRoute());};
})();
